# deploy-auth-service.yml - Versão 9 (FINAL) com Autenticação Nativa do Runner

name: Deploy Auth Service to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/auth-service/**'

jobs:
  build-and-deploy:
    name: Build and Deploy
    # O trabalho rodará no nosso robô particular
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # --- AUTENTICAÇÃO SIMPLIFICADA ---
      # Sem a chave, esta ação irá automaticamente usar a identidade da VM,
      # que já tem as permissões corretas.
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker southamerica-east1-docker.pkg.dev

      - name: Build and Push Docker image
        run: docker build -t southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }} -f ./backend/auth-service/Dockerfile ./backend/auth-service

      - name: Push Docker image
        run: docker push southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy auth-service \
            --image=southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }} \
            --region=southamerica-east1 \
            --platform=managed \
            --allow-unauthenticated
