# deploy-auth-service.yml - Versão 4 (FINAL) com correção de contexto

name: Deploy Auth Service to Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/auth-service/**'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and Push Docker image
        # ---- INÍCIO DA CORREÇÃO ----
        # AQUI ESTÁ A MUDANÇA: Adicionamos 'working-directory' para forçar
        # a execução dos comandos de dentro da pasta correta.
        working-directory: ./backend/auth-service
        run: |-
          # Configura o Docker para o Artifact Registry
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev
          
          # Constrói a imagem Docker. O "." significa "use esta pasta atual".
          docker build -t southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }} .
          
          # Envia a imagem para o Artifact Registry
          docker push southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }}
        # ---- FIM DA CORREÇÃO ----

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy auth-service \
            --image=southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }} \
            --region=southamerica-east1 \
            --platform=managed \
            --allow-unauthenticated
