# deploy-auth-service.yml - Versão FINAL com Gatilho Manual

name: Deploy Auth Service to Cloud Run

on:
  # Gatilho para acionamento manual (cria o botão "Run workflow")
  workflow_dispatch:
  
  # Gatilho automático ao alterar o código na pasta do serviço
  push:
    branches:
      - main
    paths:
      - 'backend/auth-service/**'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    # Permissões necessárias para a autenticação segura com o GCP
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and Push Docker image
        run: |-
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev
          docker build -t southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }} ./backend/auth-service
          docker push southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy auth-service \
            --image=southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/peoplepulse-repo/auth-service:${{ github.sha }} \
            --region=southamerica-east1 \
            --platform=managed \
            --allow-unauthenticated
